truncate table entidade;
truncate table categoria;
truncate table curso;

INSERT INTO entidade (Nome, Cep) VALUES (N'Unifran', 14404600);

INSERT INTO categoria (Entidade, Nome) VALUES (1, N'CIÊNCIAS ADMINISTRATIVAS');
INSERT INTO categoria (Entidade, Nome) VALUES (1, N'CIÊNCIAS BIOLÓGICAS');
INSERT INTO categoria (Entidade, Nome) VALUES (1, N'CIÊNCIAS EXATAS');
INSERT INTO categoria (Entidade, Nome) VALUES (1, N'CIÊNCIAS HUMANAS');
INSERT INTO categoria (Entidade, Nome) VALUES (1, N'CIÊNCIAS JURÍDICAS');
INSERT INTO categoria (Entidade, Nome) VALUES (1, N'CIÊNCIAS DA SAÚDE');
INSERT INTO categoria (Entidade, Nome) VALUES (1, N'CIÊNCIAS TECNOLÓGICAS');
INSERT INTO categoria (Entidade, Nome) VALUES (1, N'ARTES');

INSERT INTO curso (Categoria, Nome) VALUES (1, N'ADMINISTRAÇÃO');
INSERT INTO curso (Categoria, Nome) VALUES (1, N'AGRONEGÓCIO');
INSERT INTO curso (Categoria, Nome) VALUES (1, N'CIÊNCIAS CONTÁBEIS');
INSERT INTO curso (Categoria, Nome) VALUES (1, N'CIÊNCIAS ECONÔMICAS');
INSERT INTO curso (Categoria, Nome) VALUES (1, N'COMÉRCIO EXTERIOR');
INSERT INTO curso (Categoria, Nome) VALUES (5, N'DIREITO');
INSERT INTO curso (Categoria, Nome) VALUES (1, N'GESTÃO COMERCIAL');
INSERT INTO curso (Categoria, Nome) VALUES (1, N'GESTÃO DE RECURSOS HUMANOS');
INSERT INTO curso (Categoria, Nome) VALUES (1, N'GESTÃO FINANCEIRA');
INSERT INTO curso (Categoria, Nome) VALUES (1, N'LOGÍSTICA');
INSERT INTO curso (Categoria, Nome) VALUES (1, N'MARKETING');
INSERT INTO curso (Categoria, Nome) VALUES (1, N'PROCESSOS GERENCIAIS');
INSERT INTO curso (Categoria, Nome) VALUES (5, N'RELAÇÕES INTERNACIONAIS');
INSERT INTO curso (Categoria, Nome) VALUES (1, N'SEGURANÇA NO TRABALHO');
INSERT INTO curso (Categoria, Nome) VALUES (7, N'BIOMEDICINA');
INSERT INTO curso (Categoria, Nome) VALUES (2, N'CIÊNCIAS BIOLÓGICAS (Bacharelado)');
INSERT INTO curso (Categoria, Nome) VALUES (2, N'CIÊNCIAS BIOLÓGICAS (Licenciatura)');
INSERT INTO curso (Categoria, Nome) VALUES (7, N'EDUCAÇÃO FÍSICA (Bacharelado)');
INSERT INTO curso (Categoria, Nome) VALUES (7, N'EDUCAÇÃO FÍSICA (Licenciatura)');
INSERT INTO curso (Categoria, Nome) VALUES (7, N'ENFERMAGEM');
INSERT INTO curso (Categoria, Nome) VALUES (7, N'ESTÉTICA E COSMÉTICA');
INSERT INTO curso (Categoria, Nome) VALUES (7, N'FARMÁCIA');
INSERT INTO curso (Categoria, Nome) VALUES (7, N'FISIOTERAPIA');
INSERT INTO curso (Categoria, Nome) VALUES (7, N'FONOAUDIOLOGIA');
INSERT INTO curso (Categoria, Nome) VALUES (7, N'GASTRONOMIA');
INSERT INTO curso (Categoria, Nome) VALUES (7, N'MEDICINA');
INSERT INTO curso (Categoria, Nome) VALUES (7, N'MEDICINA VETERINÁRIA');
INSERT INTO curso (Categoria, Nome) VALUES (2, N'NUTRIÇÃO');
INSERT INTO curso (Categoria, Nome) VALUES (7, N'ODONTOLOGIA');
INSERT INTO curso (Categoria, Nome) VALUES (7, N'PSICOLOGIA');
INSERT INTO curso (Categoria, Nome) VALUES (7, N'RADIOLOGIA');
INSERT INTO curso (Categoria, Nome) VALUES (9, N'ANÁLISE E DESENVOLVIMENTO DE SISTEMAS');
INSERT INTO curso (Categoria, Nome) VALUES (9, N'CIÊNCIA DA COMPUTAÇÃO');
INSERT INTO curso (Categoria, Nome) VALUES (9, N'CST EM AUTOMAÇÃO INDUSTRIAL');
INSERT INTO curso (Categoria, Nome) VALUES (3, N'ENGENHARIA AGRONÔMICA (AGRONOMIA)');
INSERT INTO curso (Categoria, Nome) VALUES (3, N'ENGENHARIA CIVIL');
INSERT INTO curso (Categoria, Nome) VALUES (3, N'ENGENHARIA DE PRODUÇÃO');
INSERT INTO curso (Categoria, Nome) VALUES (3, N'ENGENHARIA MECÂNICA');
INSERT INTO curso (Categoria, Nome) VALUES (9, N'ENGENHARIA MECATRÔNICA');
INSERT INTO curso (Categoria, Nome) VALUES (3, N'ENGENHARIA QUÍMICA');
INSERT INTO curso (Categoria, Nome) VALUES (3, N'FÍSICA');
INSERT INTO curso (Categoria, Nome) VALUES (3, N'GESTÃO AMBIENTAL');
INSERT INTO curso (Categoria, Nome) VALUES (3, N'MANUTENÇÃO INDUSTRIAL');
INSERT INTO curso (Categoria, Nome) VALUES (3, N'MATEMÁTICA');
INSERT INTO curso (Categoria, Nome) VALUES (9, N'MECATRÔNICA INDUSTRIAL');
INSERT INTO curso (Categoria, Nome) VALUES (3, N'PRODUÇÃO SUCROALCOOLEIRA');
INSERT INTO curso (Categoria, Nome) VALUES (3, N'QUÍMICA (Bacharelado)');
INSERT INTO curso (Categoria, Nome) VALUES (3, N'QUÍMICA (Licenciatura)');
INSERT INTO curso (Categoria, Nome) VALUES (9, N'SISTEMAS DE INFORMAÇÃO');
INSERT INTO curso (Categoria, Nome) VALUES (9, N'SISTEMAS PARA INTERNET');
INSERT INTO curso (Categoria, Nome) VALUES (4, N'ARQUITETURA E URBANISMO');
INSERT INTO curso (Categoria, Nome) VALUES (10, N'ARTES VISUAIS');
INSERT INTO curso (Categoria, Nome) VALUES (4, N'CIÊNCIAS SOCIAIS (LICENCIATURA)');
INSERT INTO curso (Categoria, Nome) VALUES (10, N'DESIGN DE MODA (Tecnológico)');
INSERT INTO curso (Categoria, Nome) VALUES (10, N'DESIGN DE PRODUTO');
INSERT INTO curso (Categoria, Nome) VALUES (10, N'DESIGN GRÁFICO (Bacharelado)');
INSERT INTO curso (Categoria, Nome) VALUES (10, N'DESIGN GRÁFICO (Tecnológico)');
INSERT INTO curso (Categoria, Nome) VALUES (4, N'FORMAÇÃO DE PROF. EM PSICOLOGIA');
INSERT INTO curso (Categoria, Nome) VALUES (4, N'GEOGRAFIA');
INSERT INTO curso (Categoria, Nome) VALUES (4, N'HISTÓRIA');
INSERT INTO curso (Categoria, Nome) VALUES (4, N'JORNALISMO');
INSERT INTO curso (Categoria, Nome) VALUES (4, N'LETRAS (Tradutor/Intérprete)');
INSERT INTO curso (Categoria, Nome) VALUES (4, N'LETRAS- PORTUGUÊS');
INSERT INTO curso (Categoria, Nome) VALUES (4, N'LETRAS-PORTUGUÊS E ESPANHOL');
INSERT INTO curso (Categoria, Nome) VALUES (4, N'LETRAS-PORTUGUÊS E INGLÊS');
INSERT INTO curso (Categoria, Nome) VALUES (10, N'MODA');
INSERT INTO curso (Categoria, Nome) VALUES (4, N'PEDAGOGIA');
INSERT INTO curso (Categoria, Nome) VALUES (10, N'PUBLICIDADE E PROPAGANDA');
INSERT INTO curso (Categoria, Nome) VALUES (4, N'SERVIÇO SOCIAL');
